#@ load("@ytt:data", "data")

#@ def labels():
app: tanzu-ako-operator
#@ end
#@
#@ def dockerImage():
#@   return  ":".join(["/".join([data.values.imageRegistry, data.values.imageName]),  data.values.imageTag])
#@ end
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
---
apiVersion: v1
kind: Service
metadata:
  labels: #@ labels()
  name: ako-operator-controller-manager-metrics-service
  namespace: #@ data.values.namespace
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: #@ labels()
  name: ako-operator-controller-manager
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --metrics-addr=127.0.0.1:8080
          command:
            - /manager
          image: #@ dockerImage()
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
