# permissions for end users to edit akodeploymentconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akodeploymentconfig-editor-role
rules:
- apiGroups:
  - network.tanzu.vmware.com
  resources:
  - akodeploymentconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.tanzu.vmware.com
  resources:
  - akodeploymentconfigs/status
  verbs:
  - get
