# permissions for end users to view akodeploymentconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akodeploymentconfig-viewer-role
rules:
- apiGroups:
  - network.tanzu.vmware.com
  resources:
  - akodeploymentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.tanzu.vmware.com
  resources:
  - akodeploymentconfigs/status
  verbs:
  - get
