# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: akodeploymentconfigs.networking.tkg.tanzu.vmware.com
spec:
  conversion:
    strategy: None
