#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: network.tanzu.vmware.com/v1alpha1
kind: AKODeploymentConfig
metadata:
    name: install-ako-for-all
spec:
    cloudName: #@ data.values.AVI_CLOUD_NAME
    serviceEngineGroup: #@ data.values.AVI_SERVICE_ENGINE
    controller: #@ data.values.AVI_CONTROLLER
    adminCredentialRef:
        name: avi-controller-credentials
        namespace: #@ data.values.AVI_NAMESPACE
    certificateAuthorityRef:
        name: avi-controller-ca
        namespace: #@ data.values.AVI_NAMESPACE
    dataNetwork:
        name: #@ data.values.AVI_DATA_NETWORK
        cidr: #@ data.values.AVI_DATA_NETWORK_CIDR
        ipPools:
            - start: #@ data.values.AVI_DATA_NETWORK_IP_POOL_START
              end: #@ data.values.AVI_DATA_NETWORK_IP_POOL_END
              type: V4
    extraConfigs:
        image:
            repository: #@ data.values.AVI_AKO_IMAGE
            pullPolicy: IfNotPresent
            version: #@ data.values.AVI_AKO_IMAGE_TAG
        disableIngressClass: #@ data.values.AVI_DISABLE_INGRESS_CLASS
---
apiVersion: v1
kind: Secret
metadata:
    name: avi-controller-credentials
    namespace: #@ data.values.AVI_NAMESPACE
type: Opaque
data:
    username: #@ base64.encode(data.values.AVI_USERNAME)
    password: #@ base64.encode(data.values.AVI_PASSWORD)
---
apiVersion: v1
kind: Secret
metadata:
    name: avi-controller-ca
    namespace: #@ data.values.AVI_NAMESPACE
type: Opaque
data:
    certificateAuthorityData: #@ base64.encode(data.values.AVI_CA_DATA)
