apiVersion: v1
kind: Service
metadata:
  name: static-ip
spec:
  selector:
    app: static-ip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-ip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-ip
  template:
    metadata:
      labels:
        app: static-ip
    spec:
      serviceAccountName: default
      containers:
        - name: nginx
          image: gcr.io/kubernetes-development-244305/nginx:latest
